In [1]:
import pandas as pd
import numpy as np
import os
import ast
import matplotlib.pyplot as plt
import cv2

In [2]:
df_epi = pd.read_csv("EpiduralHemorrhageRemovedFlags.csv")

cond1 = df_epi["Correct Label"].notna()
cond2 = df_epi["Correct Label"].isna()

v1 = df_epi["Correct Label"]
v2 = df_epi["Majority Label"]

df_epi["OutLabel"] = np.select([cond1, cond2], [v1, v2])
df_epi

,Unnamed: 0,Case ID,Origin,URL,Labeling State,All Labels,Total Reads,Total Qualified Reads,Majority Label,Number of ROIs,Correct Label,Difficulty,Agreement,Comments,Internal Notes,OutLabel
0,0,1196514,ID_004c4b319.jpg,https://go.centaurlabs.com/problem/1196514,Labeled,"['[{""x"": 0.40818718, ""y"": 0.8623607}, {""x"": 0....",19.0,5.0,"[{""x"": 0.537109375, ""y"": 0.89453125}, {""x"": 0....",1.0,"[[{'x': 0.537109375, 'y': 0.89453125}, {'x': 0...",0.00,0.968851,NaN,NaN,"[[{'x': 0.537109375, 'y': 0.89453125}, {'x': 0..."
1,1,1196682,ID_0237b835f.jpg,https://go.centaurlabs.com/problem/1196682,Ready,"['[{""x"": 0.62959146, ""y"": 0.720186}, {""x"": 0.6...",51.0,28.0,"[{""x"": 0.654296875, ""y"": 0.724609375}, {""x"": 0...",1.0,NaN,NaN,0.063519,NaN,NaN,"[{""x"": 0.654296875, ""y"": 0.724609375}, {""x"": 0..."
2,2,1196477,ID_02e2d273d.jpg,https://go.centaurlabs.com/problem/1196477,Labeled,"['[{""x"": 0.35205495, ""y"": 0.34680602}, {""x"": 0...",22.0,6.0,"[{""x"": 0.46484375, ""y"": 0.357421875}, {""x"": 0....",1.0,"[[{'x': 0.46484375, 'y': 0.357421875}, {'x': 0...",0.06,0.710300,NaN,NaN,"[[{'x': 0.46484375, 'y': 0.357421875}, {'x': 0..."
3,3,1196612,ID_02f37ce84.jpg,https://go.centaurlabs.com/problem/1196612,Ready,"['[{""x"": 0.3680166, ""y"": 0.48387372}, {""x"": 0....",51.0,29.0,"[{""x"": 0.431640625, ""y"": 0.607421875}, {""x"": 0...",2.0,NaN,NaN,0.264134,NaN,NaN,"[{""x"": 0.431640625, ""y"": 0.607421875}, {""x"": 0..."
4,4,1196612,ID_02f37ce84.jpg,https://go.centaurlabs.com/problem/1196612,Ready,"['[{""x"": 0.3680166, ""y"": 0.48387372}, {""x"": 0....",51.0,29.0,"[{""x"": 0.353515625, ""y"": 0.59765625}, {""x"": 0....",2.0,NaN,NaN,0.264134,NaN,NaN,"[{""x"": 0.353515625, ""y"": 0.59765625}, {""x"": 0...."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
604,605,1196614,ID_879afbc77.jpg,https://go.centaurlabs.com/problem/1196614,Ready,['[]' '[]' '[]' '[]' '[]' '[]' '[]' '[]' '[]' ...,52.0,29.0,[],0.0,NaN,NaN,1.000000,NaN,NaN,[]
605,606,1196600,ID_af76460ee.jpg,https://go.centaurlabs.com/problem/1196600,Ready,['[]' '[]' '[]' '[]' '[]' '[]' '[]' '[]' '[]' ...,52.0,30.0,[],0.0,NaN,NaN,1.000000,NaN,NaN,[]
606,607,1196767,ID_d6d369eaa.jpg,https://go.centaurlabs.com/problem/1196767,In Progress,['[]' '[]' '[]' '[]' '[]'],77.0,5.0,[],0.0,NaN,NaN,1.000000,NaN,NaN,[]
607,608,1196539,ID_d9bfa60ed.jpg,https://go.centaurlabs.com/problem/1196539,Labeled,['[]' '[]' '[]' '[]' '[]' '[]' '[]' '[]'],20.0,8.0,[],0.0,"[[{'x': 0.443359375, 'y': 0.810546875}, {'x': ...",0.12,1.000000,NaN,NaN,"[[{'x': 0.443359375, 'y': 0.810546875}, {'x': ..."
608,609,1196955,ID_fa2874be0.jpg,https://go.centaurlabs.com/problem/1196955,Labeled,['[]' '[]' '[]' '[]' '[]' '[]' '[]'],18.0,7.0,[],0.0,"[[{'x': 0.37890625, 'y': 0.318359375}, {'x': 0...",0.14,1.000000,NaN,NaN,"[[{'x': 0.37890625, 'y': 0.318359375}, {'x': 0..."

In [3]:
df_subdur = pd.read_csv("SubduralHemorrhageRemovedFlags.csv")

cond1 = df_subdur["Correct Label"].notna()
cond2 = df_subdur["Correct Label"].isna()

v1 = df_subdur["Correct Label"]
v2 = df_subdur["Majority Label"]

df_subdur["OutLabel"] = np.select([cond1, cond2], [v1, v2])
df_subdur

,Unnamed: 0,Case ID,Origin,URL,Labeling State,All Labels,Total Reads,Total Qualified Reads,Majority Label,Number of ROIs,Correct Label,Difficulty,Agreement,Comments,Internal Notes,OutLabel
0,0,1198320,ID_0061cb462.jpg,https://go.centaurlabs.com/problem/1198320,Labeled,"['[{""x"": 0.4823523, ""y"": 0.59177}, {""x"": 0.473...",16.0,5.0,"[{""x"": 0.45703125, ""y"": 0.78125}, {""x"": 0.4570...",2.0,"[[{'x': 0.40625, 'y': 0.330078125}, {'x': 0.40...",0.29,0.949092,NaN,NaN,"[[{'x': 0.40625, 'y': 0.330078125}, {'x': 0.40..."
1,1,1198320,ID_0061cb462.jpg,https://go.centaurlabs.com/problem/1198320,Labeled,"['[{""x"": 0.4823523, ""y"": 0.59177}, {""x"": 0.473...",16.0,5.0,"[{""x"": 0.404296875, ""y"": 0.333984375}, {""x"": 0...",2.0,"[[{'x': 0.40625, 'y': 0.330078125}, {'x': 0.40...",0.29,0.949092,NaN,NaN,"[[{'x': 0.40625, 'y': 0.330078125}, {'x': 0.40..."
2,2,1198004,ID_0086b5e67.jpg,https://go.centaurlabs.com/problem/1198004,In Progress,"['[{""x"": 0.5224404, ""y"": 0.8304443}, {""x"": 0.5...",15.0,6.0,"[{""x"": 0.521484375, ""y"": 0.83203125}, {""x"": 0....",2.0,NaN,NaN,0.157037,NaN,NaN,"[{""x"": 0.521484375, ""y"": 0.83203125}, {""x"": 0...."
3,3,1198004,ID_0086b5e67.jpg,https://go.centaurlabs.com/problem/1198004,In Progress,"['[{""x"": 0.5224404, ""y"": 0.8304443}, {""x"": 0.5...",15.0,6.0,"[{""x"": 0.478515625, ""y"": 0.83984375}, {""x"": 0....",2.0,NaN,NaN,0.157037,NaN,NaN,"[{""x"": 0.478515625, ""y"": 0.83984375}, {""x"": 0...."
4,4,1198353,ID_00eb6f7cc.jpg,https://go.centaurlabs.com/problem/1198353,Labeled,"['[{""x"": 0.48163298, ""y"": 0.71568763}, {""x"": 0...",15.0,5.0,"[{""x"": 0.447265625, ""y"": 0.73828125}, {""x"": 0....",1.0,"[[{'x': 0.447265625, 'y': 0.73828125}, {'x': 0...",0.00,0.306828,NaN,NaN,"[[{'x': 0.447265625, 'y': 0.73828125}, {'x': 0..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
745,747,1197978,ID_c0bfa10d4.jpg,https://go.centaurlabs.com/problem/1197978,In Progress,"['[{""x"": 0.6507828, ""y"": 0.57011575}, {""x"": 0....",14.0,5.0,[],0.0,NaN,NaN,0.800000,NaN,NaN,[]
746,748,1198037,ID_04f4f9961.jpg,https://go.centaurlabs.com/problem/1198037,In Progress,['[]' '[]' '[]' '[]' '[]'],15.0,5.0,[],0.0,NaN,NaN,1.000000,NaN,NaN,[]
747,749,1198103,ID_39cacf303.jpg,https://go.centaurlabs.com/problem/1198103,In Progress,['[]' '[]' '[]' '[]' '[]' '[]'],15.0,6.0,[],0.0,NaN,NaN,1.000000,NaN,NaN,[]
748,750,1198171,ID_522d2c708.jpg,https://go.centaurlabs.com/problem/1198171,In Progress,['[]' '[]' '[]' '[]' '[]'],15.0,5.0,[],0.0,NaN,NaN,1.000000,NaN,NaN,[]
749,751,1198216,ID_526a44302.jpg,https://go.centaurlabs.com/problem/1198216,In Progress,['[]' '[]' '[]' '[]' '[]' '[]'],14.0,6.0,[],0.0,NaN,NaN,1.000000,NaN,NaN,[]

In [4]:
df_subarc = pd.read_csv("SubarachnoidHemorrhageRemovedFlags.csv")

cond1 = df_subarc["Correct Label"].notna()
cond2 = df_subarc["Correct Label"].isna()

v1 = df_subarc["Correct Label"]
v2 = df_subarc["Majority Label"]

df_subarc["OutLabel"] = np.select([cond1, cond2], [v1, v2])
df_subarc

,Unnamed: 0,Case ID,Origin,URL,Labeling State,All Labels,Total Reads,Total Qualified Reads,Majority Label,Number of ROIs,Correct Label,Difficulty,Agreement,Comments,Internal Notes,OutLabel
0,0,1197112,ID_001b1b944.jpg,https://go.centaurlabs.com/problem/1197112,In Progress,"['[{""x"": 0.43056944, ""y"": 0.5936399}, {""x"": 0....",16.0,5.0,"[{""x"": 0.314453125, ""y"": 0.75}, {""x"": 0.314453...",3.0,NaN,NaN,0.252748,NaN,NaN,"[{""x"": 0.314453125, ""y"": 0.75}, {""x"": 0.314453..."
1,1,1197112,ID_001b1b944.jpg,https://go.centaurlabs.com/problem/1197112,In Progress,"['[{""x"": 0.43056944, ""y"": 0.5936399}, {""x"": 0....",16.0,5.0,"[{""x"": 0.400390625, ""y"": 0.796875}, {""x"": 0.40...",3.0,NaN,NaN,0.252748,NaN,NaN,"[{""x"": 0.400390625, ""y"": 0.796875}, {""x"": 0.40..."
2,2,1197112,ID_001b1b944.jpg,https://go.centaurlabs.com/problem/1197112,In Progress,"['[{""x"": 0.43056944, ""y"": 0.5936399}, {""x"": 0....",16.0,5.0,"[{""x"": 0.556640625, ""y"": 0.302734375}, {""x"": 0...",3.0,NaN,NaN,0.252748,NaN,NaN,"[{""x"": 0.556640625, ""y"": 0.302734375}, {""x"": 0..."
3,3,1197367,ID_005f428d2.jpg,https://go.centaurlabs.com/problem/1197367,Labeled,"['[{""x"": 0.59604716, ""y"": 0.4975766}, {""x"": 0....",29.0,5.0,"[{""x"": 0.54296875, ""y"": 0.763671875}, {""x"": 0....",2.0,"[[{'x': 0.626953125, 'y': 0.30078125}, {'x': 0...",0.33,0.763632,NaN,NaN,"[[{'x': 0.626953125, 'y': 0.30078125}, {'x': 0..."
4,4,1197367,ID_005f428d2.jpg,https://go.centaurlabs.com/problem/1197367,Labeled,"['[{""x"": 0.59604716, ""y"": 0.4975766}, {""x"": 0....",29.0,5.0,"[{""x"": 0.630859375, ""y"": 0.30078125}, {""x"": 0....",2.0,"[[{'x': 0.626953125, 'y': 0.30078125}, {'x': 0...",0.33,0.763632,NaN,NaN,"[[{'x': 0.626953125, 'y': 0.30078125}, {'x': 0..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1026,1026,1197026,ID_ffb8b3408.jpg,https://go.centaurlabs.com/problem/1197026,In Progress,"['[{""x"": 0.61802936, ""y"": 0.6869475}, {""x"": 0....",15.0,5.0,"[{""x"": 0.44921875, ""y"": 0.748046875}, {""x"": 0....",1.0,NaN,NaN,0.431073,NaN,NaN,"[{""x"": 0.44921875, ""y"": 0.748046875}, {""x"": 0...."
1027,1027,1197288,ID_ffc54be74.jpg,https://go.centaurlabs.com/problem/1197288,Labeled,"['[{""x"": 0.60182124, ""y"": 0.6626198}, {""x"": 0....",25.0,6.0,"[{""x"": 0.505859375, ""y"": 0.734375}, {""x"": 0.50...",2.0,"[[{'x': 0.287109375, 'y': 0.443359375}, {'x': ...",0.15,0.351496,NaN,NaN,"[[{'x': 0.287109375, 'y': 0.443359375}, {'x': ..."
1028,1028,1197288,ID_ffc54be74.jpg,https://go.centaurlabs.com/problem/1197288,Labeled,"['[{""x"": 0.60182124, ""y"": 0.6626198}, {""x"": 0....",25.0,6.0,"[{""x"": 0.287109375, ""y"": 0.443359375}, {""x"": 0...",2.0,"[[{'x': 0.287109375, 'y': 0.443359375}, {'x': ...",0.15,0.351496,NaN,NaN,"[[{'x': 0.287109375, 'y': 0.443359375}, {'x': ..."
1029,1029,1197157,ID_0cefcaa16.jpg,https://go.centaurlabs.com/problem/1197157,Gold Standard,"['[{""x"": 0.48153853, ""y"": 0.4326744}, {""x"": 0....",16.0,5.0,[],0.0,[[]],0.00,0.833333,NaN,NaN,[[]]
1030,1030,1197175,ID_ac8229f7a.jpg,https://go.centaurlabs.com/problem/1197175,Gold Standard,"['[{""x"": 0.39485946, ""y"": 0.31588602}, {""x"": 0...",17.0,5.0,[],0.0,"[[{'x': 0.3634235, 'y': 0.3907563}, {'x': 0.36...",0.00,0.800000,NaN,NaN,"[[{'x': 0.3634235, 'y': 0.3907563}, {'x': 0.36..."

In [5]:
df_intra = pd.read_csv("IntraparenchymalHemorrhageRemovedFlags.csv")

cond1 = df_intra["Correct Label"].notna()
cond2 = df_intra["Correct Label"].isna()

v1 = df_intra["Correct Label"]
v2 = df_intra["Majority Label"]

df_intra["OutLabel"] = np.select([cond1, cond2], [v1, v2])
df_intra

,Unnamed: 0,Case ID,Origin,URL,Labeling State,All Labels,Total Reads,Total Qualified Reads,Majority Label,Number of ROIs,Correct Label,Difficulty,Agreement,Comments,Internal Notes,OutLabel
0,0,1675660,ID_0002081b6.jpg,https://go.centaurlabs.com/problem/1675660,In Progress,"['[{""x"": 0.31658885, ""y"": 0.48357323}, {""x"": 0...",22.0,9.0,"[{""x"": 0.3046875, ""y"": 0.484375}, {""x"": 0.3046...",1.0,NaN,NaN,0.224542,NaN,NaN,"[{""x"": 0.3046875, ""y"": 0.484375}, {""x"": 0.3046..."
1,1,1675942,ID_0048e60a4.jpg,https://go.centaurlabs.com/problem/1675942,In Progress,"['[{""x"": 0.54811704, ""y"": 0.5961946}, {""x"": 0....",22.0,7.0,"[{""x"": 0.5859375, ""y"": 0.640625}, {""x"": 0.5859...",1.0,NaN,NaN,0.772365,NaN,NaN,"[{""x"": 0.5859375, ""y"": 0.640625}, {""x"": 0.5859..."
2,2,1197689,ID_0057d2736.jpg,https://go.centaurlabs.com/problem/1197689,Labeled,"['[{""x"": 0.3040109, ""y"": 0.52168596}, {""x"": 0....",46.0,9.0,"[{""x"": 0.3046875, ""y"": 0.521484375}, {""x"": 0.3...",1.0,"[[{'x': 0.3046875, 'y': 0.521484375}, {'x': 0....",0.02,0.738368,NaN,NaN,"[[{'x': 0.3046875, 'y': 0.521484375}, {'x': 0...."
3,3,1197754,ID_007cac3b7.jpg,https://go.centaurlabs.com/problem/1197754,Labeled,"['[{""x"": 0.41792268, ""y"": 0.56897116}, {""x"": 0...",51.0,10.0,"[{""x"": 0.41015625, ""y"": 0.615234375}, {""x"": 0....",1.0,"[[{'x': 0.4140625, 'y': 0.6171875}, {'x': 0.41...",0.03,0.618086,NaN,NaN,"[[{'x': 0.4140625, 'y': 0.6171875}, {'x': 0.41..."
4,4,1675775,ID_00b46c6bc.jpg,https://go.centaurlabs.com/problem/1675775,In Progress,"['[{""x"": 0.82215744, ""y"": 0.20116618}, {""x"": 0...",22.0,6.0,"[{""x"": 0.365234375, ""y"": 0.693359375}, {""x"": 0...",1.0,NaN,NaN,0.006388,NaN,NaN,"[{""x"": 0.365234375, ""y"": 0.693359375}, {""x"": 0..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1278,1283,1676103,ID_2efe8b804.jpg,https://go.centaurlabs.com/problem/1676103,In Progress,['[]' '[]' '[]' '[]' '[]'],22.0,5.0,[],0.0,NaN,NaN,1.000000,NaN,NaN,[]
1279,1285,1675679,ID_4d5dac21b.jpg,https://go.centaurlabs.com/problem/1675679,In Progress,['[]' '[]' '[]' '[]' '[]' '[]'],22.0,6.0,[],0.0,NaN,NaN,1.000000,NaN,NaN,[]
1280,1286,1197797,ID_664eb0683.jpg,https://go.centaurlabs.com/problem/1197797,Labeled,['[]' '[]' '[]' '[]' '[]' '[]' '[]'],41.0,7.0,[],0.0,[[]],0.00,1.000000,NaN,NaN,[[]]
1281,1287,1197716,ID_e45ff2e50.jpg,https://go.centaurlabs.com/problem/1197716,Labeled,['[]' '[]' '[]' '[]' '[]' '[]' '[]'],47.0,7.0,[],0.0,[[]],0.00,1.000000,NaN,NaN,[[]]
1282,1288,1197511,ID_f797f771e.jpg,https://go.centaurlabs.com/problem/1197511,Labeled,['[]' '[]' '[]' '[]' '[]' '[]' '[]'],47.0,7.0,[],0.0,[[]],0.00,1.000000,NaN,NaN,[[]]

In [6]:
df_multi = pd.read_csv("MultipleHemorrhageRemovedFlags.csv")

cond1 = df_multi["Correct Label"].notna()
cond2 = df_multi["Correct Label"].isna()

v1 = df_multi["Correct Label"]
v2 = df_multi["Majority Label"]

df_multi["OutLabel"] = np.select([cond1, cond2], [v1, v2])
df_multi

,Unnamed: 0,Case ID,Origin,URL,Labeling State,All Labels,Total Reads,Total Qualified Reads,Majority Label,Number of ROIs,Correct Label,Difficulty,Agreement,Comments,Internal Notes,OutLabel
0,0,1198534,ID_01af922c3.jpg,https://go.centaurlabs.com/problem/1198534,In Progress,"['[{""x"": 0.372072, ""y"": 0.6399058}, {""x"": 0.36...",23.0,6.0,"[{""x"": 0.396484375, ""y"": 0.73046875}, {""x"": 0....",3.0,NaN,NaN,0.790347,NaN,NaN,"[{""x"": 0.396484375, ""y"": 0.73046875}, {""x"": 0...."
1,1,1198534,ID_01af922c3.jpg,https://go.centaurlabs.com/problem/1198534,In Progress,"['[{""x"": 0.372072, ""y"": 0.6399058}, {""x"": 0.36...",23.0,6.0,"[{""x"": 0.619140625, ""y"": 0.765625}, {""x"": 0.61...",3.0,NaN,NaN,0.790347,NaN,NaN,"[{""x"": 0.619140625, ""y"": 0.765625}, {""x"": 0.61..."
2,2,1198534,ID_01af922c3.jpg,https://go.centaurlabs.com/problem/1198534,In Progress,"['[{""x"": 0.372072, ""y"": 0.6399058}, {""x"": 0.36...",23.0,6.0,"[{""x"": 0.46875, ""y"": 0.607421875}, {""x"": 0.468...",3.0,NaN,NaN,0.790347,NaN,NaN,"[{""x"": 0.46875, ""y"": 0.607421875}, {""x"": 0.468..."
3,3,1198791,ID_01c457a64.jpg,https://go.centaurlabs.com/problem/1198791,Labeled,"['[{""x"": 0.40734115, ""y"": 0.5586468}, {""x"": 0....",34.0,6.0,"[{""x"": 0.4375, ""y"": 0.7109375}, {""x"": 0.4375, ...",3.0,"[[{'x': 0.548828125, 'y': 0.6796875}, {'x': 0....",0.48,0.124994,NaN,NaN,"[[{'x': 0.548828125, 'y': 0.6796875}, {'x': 0...."
4,4,1198791,ID_01c457a64.jpg,https://go.centaurlabs.com/problem/1198791,Labeled,"['[{""x"": 0.40734115, ""y"": 0.5586468}, {""x"": 0....",34.0,6.0,"[{""x"": 0.546875, ""y"": 0.671875}, {""x"": 0.54687...",3.0,"[[{'x': 0.548828125, 'y': 0.6796875}, {'x': 0....",0.48,0.124994,NaN,NaN,"[[{'x': 0.548828125, 'y': 0.6796875}, {'x': 0...."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1042,1049,1198749,ID_feef88292.jpg,https://go.centaurlabs.com/problem/1198749,In Progress,"['[{""x"": 0.62021834, ""y"": 0.4173323}, {""x"": 0....",23.0,5.0,"[{""x"": 0.53515625, ""y"": 0.556640625}, {""x"": 0....",2.0,NaN,NaN,0.507757,NaN,NaN,"[{""x"": 0.53515625, ""y"": 0.556640625}, {""x"": 0...."
1043,1050,1198944,ID_ff88e4f59.jpg,https://go.centaurlabs.com/problem/1198944,In Progress,"['[{""x"": 0.571793, ""y"": 0.7068149}, {""x"": 0.57...",23.0,6.0,"[{""x"": 0.5859375, ""y"": 0.728515625}, {""x"": 0.5...",1.0,NaN,NaN,0.251714,NaN,NaN,"[{""x"": 0.5859375, ""y"": 0.728515625}, {""x"": 0.5..."
1044,1051,1198747,ID_ffd581895.jpg,https://go.centaurlabs.com/problem/1198747,Labeled,"['[{""x"": 0.37266213, ""y"": 0.5361894}, {""x"": 0....",26.0,6.0,"[{""x"": 0.517578125, ""y"": 0.578125}, {""x"": 0.51...",3.0,"[[{'x': 0.3671875, 'y': 0.666015625}, {'x': 0....",0.14,0.672953,NaN,NaN,"[[{'x': 0.3671875, 'y': 0.666015625}, {'x': 0...."
1045,1052,1198747,ID_ffd581895.jpg,https://go.centaurlabs.com/problem/1198747,Labeled,"['[{""x"": 0.37266213, ""y"": 0.5361894}, {""x"": 0....",26.0,6.0,"[{""x"": 0.341796875, ""y"": 0.65625}, {""x"": 0.341...",3.0,"[[{'x': 0.3671875, 'y': 0.666015625}, {'x': 0....",0.14,0.672953,NaN,NaN,"[[{'x': 0.3671875, 'y': 0.666015625}, {'x': 0...."
1046,1053,1198747,ID_ffd581895.jpg,https://go.centaurlabs.com/problem/1198747,Labeled,"['[{""x"": 0.37266213, ""y"": 0.5361894}, {""x"": 0....",26.0,6.0,"[{""x"": 0.564453125, ""y"": 0.4921875}, {""x"": 0.5...",3.0,"[[{'x': 0.3671875, 'y': 0.666015625}, {'x': 0....",0.14,0.672953,NaN,NaN,"[[{'x': 0.3671875, 'y': 0.666015625}, {'x': 0...."

In [7]:
df_masks = pd.concat([df_multi, df_intra, df_subarc, df_subdur, df_epi], ignore_index=True)
df_masks

,Unnamed: 0,Case ID,Origin,URL,Labeling State,All Labels,Total Reads,Total Qualified Reads,Majority Label,Number of ROIs,Correct Label,Difficulty,Agreement,Comments,Internal Notes,OutLabel
0,0,1198534,ID_01af922c3.jpg,https://go.centaurlabs.com/problem/1198534,In Progress,"['[{""x"": 0.372072, ""y"": 0.6399058}, {""x"": 0.36...",23.0,6.0,"[{""x"": 0.396484375, ""y"": 0.73046875}, {""x"": 0....",3.0,NaN,NaN,0.790347,NaN,NaN,"[{""x"": 0.396484375, ""y"": 0.73046875}, {""x"": 0...."
1,1,1198534,ID_01af922c3.jpg,https://go.centaurlabs.com/problem/1198534,In Progress,"['[{""x"": 0.372072, ""y"": 0.6399058}, {""x"": 0.36...",23.0,6.0,"[{""x"": 0.619140625, ""y"": 0.765625}, {""x"": 0.61...",3.0,NaN,NaN,0.790347,NaN,NaN,"[{""x"": 0.619140625, ""y"": 0.765625}, {""x"": 0.61..."
2,2,1198534,ID_01af922c3.jpg,https://go.centaurlabs.com/problem/1198534,In Progress,"['[{""x"": 0.372072, ""y"": 0.6399058}, {""x"": 0.36...",23.0,6.0,"[{""x"": 0.46875, ""y"": 0.607421875}, {""x"": 0.468...",3.0,NaN,NaN,0.790347,NaN,NaN,"[{""x"": 0.46875, ""y"": 0.607421875}, {""x"": 0.468..."
3,3,1198791,ID_01c457a64.jpg,https://go.centaurlabs.com/problem/1198791,Labeled,"['[{""x"": 0.40734115, ""y"": 0.5586468}, {""x"": 0....",34.0,6.0,"[{""x"": 0.4375, ""y"": 0.7109375}, {""x"": 0.4375, ...",3.0,"[[{'x': 0.548828125, 'y': 0.6796875}, {'x': 0....",0.48,0.124994,NaN,NaN,"[[{'x': 0.548828125, 'y': 0.6796875}, {'x': 0...."
4,4,1198791,ID_01c457a64.jpg,https://go.centaurlabs.com/problem/1198791,Labeled,"['[{""x"": 0.40734115, ""y"": 0.5586468}, {""x"": 0....",34.0,6.0,"[{""x"": 0.546875, ""y"": 0.671875}, {""x"": 0.54687...",3.0,"[[{'x': 0.548828125, 'y': 0.6796875}, {'x': 0....",0.48,0.124994,NaN,NaN,"[[{'x': 0.548828125, 'y': 0.6796875}, {'x': 0...."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4715,605,1196614,ID_879afbc77.jpg,https://go.centaurlabs.com/problem/1196614,Ready,['[]' '[]' '[]' '[]' '[]' '[]' '[]' '[]' '[]' ...,52.0,29.0,[],0.0,NaN,NaN,1.000000,NaN,NaN,[]
4716,606,1196600,ID_af76460ee.jpg,https://go.centaurlabs.com/problem/1196600,Ready,['[]' '[]' '[]' '[]' '[]' '[]' '[]' '[]' '[]' ...,52.0,30.0,[],0.0,NaN,NaN,1.000000,NaN,NaN,[]
4717,607,1196767,ID_d6d369eaa.jpg,https://go.centaurlabs.com/problem/1196767,In Progress,['[]' '[]' '[]' '[]' '[]'],77.0,5.0,[],0.0,NaN,NaN,1.000000,NaN,NaN,[]
4718,608,1196539,ID_d9bfa60ed.jpg,https://go.centaurlabs.com/problem/1196539,Labeled,['[]' '[]' '[]' '[]' '[]' '[]' '[]' '[]'],20.0,8.0,[],0.0,"[[{'x': 0.443359375, 'y': 0.810546875}, {'x': ...",0.12,1.000000,NaN,NaN,"[[{'x': 0.443359375, 'y': 0.810546875}, {'x': ..."
4719,609,1196955,ID_fa2874be0.jpg,https://go.centaurlabs.com/problem/1196955,Labeled,['[]' '[]' '[]' '[]' '[]' '[]' '[]'],18.0,7.0,[],0.0,"[[{'x': 0.37890625, 'y': 0.318359375}, {'x': 0...",0.14,1.000000,NaN,NaN,"[[{'x': 0.37890625, 'y': 0.318359375}, {'x': 0..."

In [8]:
df_masks = df_masks[["Case ID", "Origin", "All Labels", "OutLabel"]]
df_masks = df_masks[df_masks["OutLabel"] != '[]']
df_masks = df_masks[df_masks["OutLabel"] != '[[], []]']
df_masks["OutLabel"] = df_masks["OutLabel"].apply(lambda x: ast.literal_eval(x))
df_masks["All Labels"] = df_masks["All Labels"].apply(lambda x: ast.literal_eval(x))

In [9]:
def flat(x):
    res = []
    for i in x:
        if type(i) is list:
            res.extend(i)
    return res if len(res) > 1 else x

def pull(x):
    res = []
    for i in x:
        if type(i) is dict:
            res.append((i['x'], i['y']))
    return res if len(res) > 1 else x

In [10]:
df_masks["OutLabel"] = df_masks["OutLabel"].apply(lambda x: flat(x))
df_masks["All Labels"] = df_masks["All Labels"].apply(lambda x: flat(x))
df_masks

,Case ID,Origin,All Labels,OutLabel
0,1198534,ID_01af922c3.jpg,"[[{""x"": 0.372072, ""y"": 0.6399058}, {""x"": 0.364...","[{'x': 0.396484375, 'y': 0.73046875}, {'x': 0...."
1,1198534,ID_01af922c3.jpg,"[[{""x"": 0.372072, ""y"": 0.6399058}, {""x"": 0.364...","[{'x': 0.619140625, 'y': 0.765625}, {'x': 0.61..."
2,1198534,ID_01af922c3.jpg,"[[{""x"": 0.372072, ""y"": 0.6399058}, {""x"": 0.364...","[{'x': 0.46875, 'y': 0.607421875}, {'x': 0.468..."
3,1198791,ID_01c457a64.jpg,"[[{""x"": 0.40734115, ""y"": 0.5586468}, {""x"": 0.4...","[{'x': 0.548828125, 'y': 0.6796875}, {'x': 0.5..."
4,1198791,ID_01c457a64.jpg,"[[{""x"": 0.40734115, ""y"": 0.5586468}, {""x"": 0.4...","[{'x': 0.548828125, 'y': 0.6796875}, {'x': 0.5..."
...,...,...,...,...
4699,1196596,ID_a297d5101.jpg,"[[{""x"": 0.75402844, ""y"": 0.68062687}, {""x"": 0....","[{'x': 0.541015625, 'y': 0.8125}, {'x': 0.5410..."
4700,1196523,ID_aa6b7bf5d.jpg,"[[{""x"": 0.2169128, ""y"": 0.3310322}, {""x"": 0.21...","[{'x': 0.220703125, 'y': 0.451171875}, {'x': 0..."
4712,1196860,ID_f82e15eb5.jpg,"[[{""x"": 0.429657, ""y"": 0.864296}, {""x"": 0.4877...","[{'x': 0.48046875, 'y': 0.8828125}, {'x': 0.48..."
4718,1196539,ID_d9bfa60ed.jpg,[[][][][][][][][]],"[{'x': 0.443359375, 'y': 0.810546875}, {'x': 0..."
4719,1196955,ID_fa2874be0.jpg,[[][][][][][][]],"[{'x': 0.37890625, 'y': 0.318359375}, {'x': 0...."

In [11]:
df_masks["OutLabel"] = df_masks["OutLabel"].apply(lambda x: pull(x))
df_masks["All Labels"] = df_masks["All Labels"].apply(lambda x: pull(x))
df_masks

,Case ID,Origin,All Labels,OutLabel
0,1198534,ID_01af922c3.jpg,"[[{""x"": 0.372072, ""y"": 0.6399058}, {""x"": 0.364...","[(0.396484375, 0.73046875), (0.396484375, 0.72..."
1,1198534,ID_01af922c3.jpg,"[[{""x"": 0.372072, ""y"": 0.6399058}, {""x"": 0.364...","[(0.619140625, 0.765625), (0.619140625, 0.7617..."
2,1198534,ID_01af922c3.jpg,"[[{""x"": 0.372072, ""y"": 0.6399058}, {""x"": 0.364...","[(0.46875, 0.607421875), (0.46875, 0.60546875)..."
3,1198791,ID_01c457a64.jpg,"[[{""x"": 0.40734115, ""y"": 0.5586468}, {""x"": 0.4...","[(0.548828125, 0.6796875), (0.548828125, 0.675..."
4,1198791,ID_01c457a64.jpg,"[[{""x"": 0.40734115, ""y"": 0.5586468}, {""x"": 0.4...","[(0.548828125, 0.6796875), (0.548828125, 0.675..."
...,...,...,...,...
4699,1196596,ID_a297d5101.jpg,"[[{""x"": 0.75402844, ""y"": 0.68062687}, {""x"": 0....","[(0.541015625, 0.8125), (0.541015625, 0.810546..."
4700,1196523,ID_aa6b7bf5d.jpg,"[[{""x"": 0.2169128, ""y"": 0.3310322}, {""x"": 0.21...","[(0.220703125, 0.451171875), (0.220703125, 0.4..."
4712,1196860,ID_f82e15eb5.jpg,"[[{""x"": 0.429657, ""y"": 0.864296}, {""x"": 0.4877...","[(0.48046875, 0.8828125), (0.48046875, 0.88085..."
4718,1196539,ID_d9bfa60ed.jpg,[[][][][][][][][]],"[(0.443359375, 0.810546875), (0.443359375, 0.8..."
4719,1196955,ID_fa2874be0.jpg,[[][][][][][][]],"[(0.37890625, 0.318359375), (0.37890625, 0.316..."

In [12]:
df = df_masks.groupby('Case ID', sort=False).agg({'Origin': lambda x: x, 'All Labels': lambda x: x,'OutLabel': lambda x: x})
df = df.reset_index()
df

,Case ID,Origin,All Labels,OutLabel
0,1198534,"[ID_01af922c3.jpg, ID_01af922c3.jpg, ID_01af92...","[[[{""x"": 0.372072, ""y"": 0.6399058}, {""x"": 0.36...","[[(0.396484375, 0.73046875), (0.396484375, 0.7..."
1,1198791,"[ID_01c457a64.jpg, ID_01c457a64.jpg, ID_01c457...","[[[{""x"": 0.40734115, ""y"": 0.5586468}, {""x"": 0....","[[(0.548828125, 0.6796875), (0.548828125, 0.67..."
2,1198657,"[ID_0230aaa10.jpg, ID_0230aaa10.jpg]","[[[{""x"": 0.7303207, ""y"": 0.7609329}, {""x"": 0.6...","[[(0.76171875, 0.646484375), (0.76171875, 0.64..."
3,1198623,"[ID_03d9d46c6.jpg, ID_03d9d46c6.jpg, ID_03d9d4...","[[[{""x"": 0.4771661, ""y"": 0.17315423}, {""x"": 0....","[[(0.541015625, 0.7734375), (0.541015625, 0.77..."
4,1198886,"[ID_0449d114e.jpg, ID_0449d114e.jpg]","[[[{""x"": 0.39765015, ""y"": 0.7408349}, {""x"": 0....","[[(0.330078125, 0.3984375), (0.330078125, 0.39..."
...,...,...,...,...
2935,1196596,ID_a297d5101.jpg,"[[{""x"": 0.75402844, ""y"": 0.68062687}, {""x"": 0....","[(0.541015625, 0.8125), (0.541015625, 0.810546..."
2936,1196523,ID_aa6b7bf5d.jpg,"[[{""x"": 0.2169128, ""y"": 0.3310322}, {""x"": 0.21...","[(0.220703125, 0.451171875), (0.220703125, 0.4..."
2937,1196860,ID_f82e15eb5.jpg,"[[{""x"": 0.429657, ""y"": 0.864296}, {""x"": 0.4877...","[(0.48046875, 0.8828125), (0.48046875, 0.88085..."
2938,1196539,ID_d9bfa60ed.jpg,[[][][][][][][][]],"[(0.443359375, 0.810546875), (0.443359375, 0.8..."
2939,1196955,ID_fa2874be0.jpg,[[][][][][][][]],"[(0.37890625, 0.318359375), (0.37890625, 0.316..."

In [13]:
directory = r'C:\Users\Scott\Documents\Masks'
filename = r'savedImage.png'

In [14]:
ouch = 0

In [20]:
cnt = 0
for lopts in df["OutLabel"]:
    orgjpeg = df['Origin'][cnt][0] if type(df['Origin'][cnt]) is np.ndarray else df['Origin'][cnt]
    fname = orgjpeg.split('.')[0] + 'mask' + '.png'
    canvas = np.zeros((512, 512,3), np.uint8)
    ouch = cnt
    if type(lopts) is np.ndarray:
        for p in lopts:
            if p != [[]]:
                pts = np.array([[int(x*512), int(y*512)] for (x,y) in p])
                cv2.drawContours(canvas, [pts],-1, (0,255,0), 3)
                cv2.fillPoly(canvas, [pts], color=(255,255,255))
    elif lopts != [[]]:
            pts = np.array([[int(x*512), int(y*512)] for (x,y) in lopts])
            cv2.drawContours(canvas, [pts],-1, (0,255,0), 3)
            cv2.fillPoly(canvas, [pts], color=(255,255,255))
    os.chdir(directory)
    cv2.imwrite(rf'{fname}', canvas)
    cnt += 1

In [21]:
ouch

2939